version: "3.8"
services:
#  language-server-cli:
#    build:
#      context: .
#      dockerfile: qsharp-compiler/src/QsCompiler/LanguageServer/Dockerfile
#    image: language-server-cli
#    container_name: language-server-cli
#    ports:
#      - "8091:8091"
  language-server:
    build:
      context: .
      dockerfile: qsharp-compiler-mirror/src/QsCompiler/ServerRunner/Dockerfile
    image: language-server
    container_name: language-server
    ports:
      - "8091:8091"
  explorer:
    build:
      context: .
      dockerfile: Explorer/Dockerfile
    image: explorer
    container_name: explorer
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - language-server
