version: "3.8"
services:
  language-server:
    build:
      context: qsharp-compiler-mirror
    image: language-server
    container_name: language-server
    ports:
      - "8091:8091"
  explorer:
    build:
      context: .
    image: explorer
    container_name: explorer
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - language-server
